export const data = [
  {
    id: "1",
    title: "Certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "2",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "3",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "4",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "5",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "6",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "7",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
  {
    id: "8",
    title: "certificate",
    desc: "Industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    image: "null",
    link: "null",
  },
];
