export const data = [
  {
    id: "1",
    title: "Certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "2",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "3",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "4",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "5",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "6",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "7",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
  {
    id: "8",
    title: "certificate",
    desc: "ini sertifikat",
    image: "null",
    link: "null",
  },
];
